# Generated by Django 3.1.2 on 2020-11-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid',
            name='type',
            field=models.CharField(choices=[('foundation', 'foundation'), ('mains', 'mains'), ('preliminary', 'preliminary'), ('free', 'free')], default='free', max_length=20),
        ),
    ]
