# Generated by Django 3.1.2 on 2020-11-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201123_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
    ]
