# Generated by Django 3.1.2 on 2020-11-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
