# Generated by Django 3.1.2 on 2020-11-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
