# Generated by Django 3.1.2 on 2020-11-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lessons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lessons',
            new_name='lesson',
        ),
    ]
