# Generated by Django 3.1.2 on 2020-11-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20201125_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
